# Generated by Django 3.2.7 on 2024-05-03 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Email',
        ),
    ]
