# Generated by Django 3.2.7 on 2024-09-23 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
