# Generated by Django 3.2.7 on 2024-09-23 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0002_email_read'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(max_length=254)),
                ('response_subject', models.CharField(max_length=100)),
                ('response_message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rsponses', to='emails.email')),
            ],
        ),
    ]
