# Generated by Django 3.2.7 on 2024-10-05 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0004_emailmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmessage',
            name='status',
            field=models.CharField(blank=True, choices=[('sending', 'sending'), ('sent', 'sent'), ('failed', 'failed')], default='sending', max_length=255),
        ),
        migrations.AlterField(
            model_name='emailmessage',
            name='subject',
            field=models.CharField(max_length=355),
        ),
    ]
