# Generated by Django 3.2.7 on 2024-07-12 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('whatsappAPI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wa_id', models.CharField(max_length=20)),
                ('profile_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField()),
                ('text_body', models.TextField()),
                ('message_type', models.CharField(max_length=50)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whatsappAPI.contact')),
            ],
        ),
        migrations.CreateModel(
            name='WhatsAppBusinessAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(max_length=255)),
                ('display_phone_number', models.CharField(max_length=20)),
                ('phone_number_id', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Whatsappuser',
        ),
        migrations.AddField(
            model_name='message',
            name='whatsapp_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whatsappAPI.whatsappbusinessaccount'),
        ),
    ]
