# Generated by Django 3.2.7 on 2024-08-26 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('whatsappAPI', '0003_auto_20240819_0313'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=100, unique=True)),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('document', 'Document'), ('sticker', 'Sticker')], max_length=20)),
                ('body', models.TextField(blank=True, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('message_mode', models.CharField(choices=[('sent message', 'Sent message'), ('received message', 'Received message')], default='sent message', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('sent', 'sent')], default='pending', max_length=20)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='whatsappAPI.contact')),
            ],
        ),
        migrations.CreateModel(
            name='ReceivedMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=100, unique=True)),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('document', 'Document'), ('sticker', 'Sticker')], max_length=20)),
                ('body', models.TextField(blank=True, null=True)),
                ('media_id', models.CharField(blank=True, max_length=100, null=True)),
                ('mime_type', models.CharField(blank=True, max_length=100, null=True)),
                ('timestamp', models.DateTimeField()),
                ('message_mode', models.CharField(choices=[('sent message', 'Sent message'), ('received message', 'Received message')], default='received message', max_length=20)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recieved_messages', to='whatsappAPI.contact')),
            ],
        ),
        migrations.AlterField(
            model_name='status',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='whatsappAPI.receivedmessage'),
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
