# Generated by Django 3.2.7 on 2024-08-26 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsappAPI', '0004_auto_20240826_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receivedmessage',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
