# Generated by Django 3.2.7 on 2024-08-31 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsappAPI', '0005_auto_20240826_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='receivedmessage',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
