# Generated by Django 3.2.7 on 2024-08-31 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whatsappAPI', '0006_receivedmessage_seen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receivedmessage',
            name='seen',
        ),
    ]
