# Generated by Django 3.2.7 on 2024-09-03 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsappAPI', '0008_receivedmessage_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='receivedmessage',
            name='animated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='receivedmessage',
            name='caption',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receivedmessage',
            name='filename',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
