# Generated by Django 3.2.7 on 2024-09-25 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('whatsappAPI', '0009_auto_20240903_0358'),
    ]

    operations = [
        migrations.CreateModel(
            name='WAMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=100, unique=True)),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('document', 'Document'), ('sticker', 'Sticker')], max_length=20)),
                ('body', models.TextField(blank=True, null=True)),
                ('media_id', models.CharField(blank=True, max_length=100, null=True)),
                ('mime_type', models.CharField(blank=True, max_length=100, null=True)),
                ('filename', models.CharField(blank=True, max_length=100, null=True)),
                ('animated', models.BooleanField(default=False)),
                ('caption', models.TextField(blank=True, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('message_mode', models.CharField(choices=[('received', 'Received Message'), ('sent', 'Sent Message')], max_length=20)),
                ('seen', models.BooleanField(default=False)),
                ('status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('sent', 'Sent')], max_length=20, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='whatsappAPI.contact')),
            ],
        ),
        migrations.RemoveField(
            model_name='receivedmessage',
            name='contact',
        ),
        migrations.DeleteModel(
            name='SentMessage',
        ),
        migrations.AlterField(
            model_name='status',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='whatsappAPI.wamessage'),
        ),
        migrations.DeleteModel(
            name='ReceivedMessage',
        ),
    ]
