# Generated by Django 3.2.7 on 2024-09-25 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsappAPI', '0010_auto_20240925_0501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wamessage',
            name='body',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='wamessage',
            name='caption',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='wamessage',
            name='filename',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='wamessage',
            name='link',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='wamessage',
            name='media_id',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='wamessage',
            name='message_mode',
            field=models.CharField(choices=[('received', 'Received Message'), ('sent', 'Sent Message')], default='received', max_length=20),
        ),
        migrations.AlterField(
            model_name='wamessage',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('document', 'Document'), ('sticker', 'Sticker')], default='text', max_length=20),
        ),
        migrations.AlterField(
            model_name='wamessage',
            name='mime_type',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='wamessage',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('sent', 'Sent')], default='pending', max_length=20, null=True),
        ),
    ]
