# Generated by Django 3.2.7 on 2024-09-25 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsappAPI', '0011_auto_20240925_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wamessage',
            name='body',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='wamessage',
            name='caption',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='wamessage',
            name='filename',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='wamessage',
            name='link',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='wamessage',
            name='media_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='wamessage',
            name='mime_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='wamessage',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('sent', 'Sent')], default='pending', max_length=20),
        ),
    ]
