# Generated by Django 3.2.7 on 2024-09-25 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsappAPI', '0012_auto_20240925_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wamessage',
            name='link',
            field=models.URLField(blank=True, default='https://www.example.com'),
        ),
    ]
