# Generated by Django 3.2.7 on 2024-10-05 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsappAPI', '0013_alter_wamessage_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wamessage',
            name='message_mode',
            field=models.CharField(choices=[('received', 'received'), ('sent', 'sent')], default='received', max_length=20),
        ),
    ]
