# Generated by Django 3.2.7 on 2024-10-10 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsappAPI', '0014_alter_wamessage_message_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='WATemplateSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', models.CharField(choices=[('textonly', 'Text Only'), ('textwithimage', 'Text with Image'), ('textwithvideo', 'Text with Video'), ('textwithaudio', 'Text with Audio'), ('textwithdocument', 'Text with Document'), ('textwithCTA', 'Text with Call to Action (CTA)')], default='textonly', max_length=50, verbose_name='Template Type')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Message Text')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Optional Link')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'WhatsApp Template',
                'verbose_name_plural': 'WhatsApp Templates',
            },
        ),
    ]
