# Generated by Django 3.2.7 on 2024-10-10 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsappAPI', '0015_watemplateschema'),
    ]

    operations = [
        migrations.AddField(
            model_name='watemplateschema',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'pending'), ('sent', 'sent'), ('failed', 'failed')], default='pending', max_length=255),
        ),
        migrations.AddField(
            model_name='watemplateschema',
            name='title',
            field=models.CharField(default='None', max_length=300, verbose_name='Message Title'),
        ),
    ]
