# Generated by Django 3.2.7 on 2024-10-10 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsappAPI', '0016_auto_20241010_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watemplateschema',
            name='title',
            field=models.CharField(default='No Title', max_length=300, verbose_name='Message Title'),
        ),
    ]
