# Generated by Django 3.2.7 on 2024-05-29 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_auto_20240528_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
