# Generated by Django 3.2.7 on 2024-07-19 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidoes', '0010_auto_20240717_0100'),
        ('payments', '0004_orders_service_delivered'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='vidoes',
            field=models.ManyToManyField(to='vidoes.Video'),
        ),
    ]
