# Generated by Django 3.2.7 on 2024-07-19 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_orders_vidoes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='vidoes',
            new_name='videos',
        ),
    ]
