# get all entries for a School
POST http://127.0.0.1:8000/authapi/verifyuser/
Content-Type: application/json

{
    "email": "chiagoziendukwe90@gmail.com",
    "password": "Sirnduu1@"
  }

###
GET http://127.0.0.1:8000/authapi/getUsers/

###
# get send a whatsapp message
POST http://127.0.0.1:8000/whatsappAPI/send-template-message/
content-type: application/json

{
    "to_phone_number": "2348080982606",
    "template_name": "Hello world",
    "language_code": "en_US"
}

###
# recieve whatsapp messages
POST http://127.0.0.1:8000/webhook/


###
POST http://127.0.0.1:8000/whatsappAPI/reply_message/
content-type: application/json

{
    "to": "2348080982606",
    "type": "text",
    "body": "we are working on it now , thanks for the Remainder"
}

# get all products
###
GET http://127.0.0.1:8000/productsapi/products/1/


# get all services
###
GET http://127.0.0.1:8000/servicesapi/services/1/

# get all vidoes
###
GET http://127.0.0.1:8000/vidoesapi/videos/1/


# get batch of Articles
###
GET http://127.0.0.1:8000/blogsapi/orgblogs/1/?page=1&page_size=10

# call apis 
###
GET http://127.0.0.1:8000/paymentsapi/getcustomerscount/1/