# Generated by Django 3.2.7 on 2024-06-10 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ICCapp', '0002_notifications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='author',
        ),
        migrations.AddField(
            model_name='testimonial',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='testimonials/images'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='name',
            field=models.CharField(default='Anonymous', max_length=100),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='role',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
