# Generated by Django 3.2.7 on 2024-06-11 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ICCapp', '0004_auto_20240611_0252'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='whatsapplink',
            new_name='instagramlink',
        ),
        migrations.AddField(
            model_name='staff',
            name='linkedinlink',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
