# Generated by Django 3.2.7 on 2024-06-11 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ICCapp', '0005_auto_20240611_0254'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
