# Generated by Django 3.2.7 on 2024-06-20 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ICCapp', '0006_subscription_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='facebooklink',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='instagramlink',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='twitterlink',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='whatsapplink',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
