# Generated by Django 3.2.7 on 2024-06-27 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ICCapp', '0008_auto_20240627_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='departments/images'),
        ),
    ]
