# Generated by Django 3.2.7 on 2024-07-02 17:29

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ICCapp', '0009_department_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='privacy_policy',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='terms_of_use',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
