# Generated by Django 3.2.7 on 2024-07-12 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ICCapp', '0011_organization_tiktoklink'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='linkedinlink',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='youtubechannel',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
