# Generated by Django 3.2.7 on 2024-10-12 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ICCapp', '0012_auto_20240712_1328'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notifications',
        ),
    ]
