# Generated by Django 5.2.6 on 2025-09-21 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ICCapp', '0015_auto_20241128_0933'),
    ]

    operations = [
        migrations.CreateModel(
            name='RichTextEditorImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='richtext/images')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
