# Generated by Django 3.2.7 on 2024-07-15 12:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vidoes', '0002_video_userids_that_bought_this_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='category',
        ),
        migrations.RemoveField(
            model_name='video',
            name='userIDs_that_bought_this_video',
        ),
        migrations.AddField(
            model_name='video',
            name='userIDs_that_bought_this_video',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
