# Generated by Django 3.2.7 on 2024-07-16 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidoes', '0003_auto_20240715_1346'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AddField(
            model_name='video',
            name='video_token',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
