# Generated by Django 3.2.7 on 2024-07-16 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vidoes', '0005_video_free'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
