# Generated by Django 3.2.7 on 2024-07-16 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidoes', '0006_alter_category_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='category',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='video',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
