# Generated by Django 3.2.7 on 2024-07-19 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidoes', '0010_auto_20240717_0100'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='number_of_times_bought',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
