# Generated by Django 3.2.7 on 2024-05-31 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CBTpractice', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='testMark',
        ),
    ]
