# Generated by Django 3.2.7 on 2024-05-31 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CBTpractice', '0005_auto_20240531_1145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='testSubject',
        ),
        migrations.AddField(
            model_name='test',
            name='testSubject',
            field=models.ManyToManyField(to='CBTpractice.Subject'),
        ),
    ]
