# Generated by Django 3.2.7 on 2025-07-24 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CBTpractice', '0007_auto_20240617_0356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='correctAnswer',
        ),
        migrations.AddField(
            model_name='answer',
            name='isCorrect',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
