# Generated by Django 3.2.7 on 2025-08-06 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CBTpractice', '0008_auto_20250724_1159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testresult',
            name='tests',
        ),
        migrations.AddField(
            model_name='testresult',
            name='test',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CBTpractice.test'),
        ),
        migrations.AddField(
            model_name='testresult',
            name='test_submission_details',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='test',
            name='testSubject',
            field=models.ManyToManyField(related_name='tests', to='CBTpractice.Subject'),
        ),
    ]
