# Generated by Django 3.2.7 on 2024-05-28 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='number_of_times_bought',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='service',
            name='preview',
            field=models.ImageField(null=True, upload_to='services/'),
        ),
        migrations.AddField(
            model_name='service',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
