# Generated by Django 3.2.7 on 2024-05-28 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_service_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='number_of_times_bought',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='rating',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
