# Generated by Django 3.2.7 on 2024-05-29 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_auto_20240528_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('service', 'service'), ('application', 'application'), ('Other', 'Other')], default='service', max_length=100),
        ),
    ]
