# Generated by Django 3.2.7 on 2024-05-29 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_service_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to='services/'),
        ),
    ]
