# Generated by Django 3.2.7 on 2024-06-13 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_alter_service_preview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='rating',
        ),
    ]
