# Generated by Django 3.2.7 on 2024-06-22 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_remove_service_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('service', 'service'), ('application', 'application'), ('Olevel', 'Olevel'), ('Jamb', 'Jamb'), ('PostUTME', 'PostUTME'), ('Tutorials', 'Tutorials'), ('Clearance', 'Clearance'), ('Others', 'Others')], default='service', max_length=100),
        ),
    ]
