# Generated by Django 3.2.7 on 2024-06-22 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_alter_service_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('service', 'service'), ('application', 'application'), ('Olevel', 'Olevel'), ('Jamb', 'Jamb'), ('PostUTME', 'PostUTME'), ('Tutorials', 'Tutorials'), ('Clearance', 'Clearance'), ('Others', 'Others')], default='Others', max_length=100),
        ),
    ]
