# Generated by Django 3.2.7 on 2024-06-23 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_service_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
