# Generated by Django 3.2.7 on 2024-07-07 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_category_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['-updated_at']},
        ),
    ]
