# Generated by Django 3.2.7 on 2024-07-15 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0014_auto_20240714_2036'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='usersID_that_purchased_service',
            new_name='userIDs_that_bought_this_service',
        ),
    ]
