# Generated by Django 3.2.7 on 2024-07-15 12:10

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0015_rename_usersid_that_purchased_service_service_userids_that_bought_this_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_flow',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
