# Generated by Django 3.2.7 on 2024-07-26 15:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0018_service_service_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='userIDs_whose_services_have_been_completed',
            field=models.ManyToManyField(blank=True, related_name='userIDs_whose_services_have_been_completed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='service',
            name='userIDs_that_bought_this_service',
            field=models.ManyToManyField(blank=True, related_name='userIDs_that_bought_this_service', to=settings.AUTH_USER_MODEL),
        ),
    ]
