# Generated by Django 3.2.7 on 2024-10-14 20:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0019_auto_20240726_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='userIDs_whose_services_is_in_progress',
            field=models.ManyToManyField(blank=True, related_name='userIDs_whose_services_is_in_progress', to=settings.AUTH_USER_MODEL),
        ),
    ]
