# Generated by Django 3.2.7 on 2024-10-22 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0020_service_userids_whose_services_is_in_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='details_form_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
