# Generated by Django 3.2.7 on 2024-05-22 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_customuser_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='emailIsVerified',
            field=models.BooleanField(default=False),
        ),
    ]
