# Generated by Django 3.2.7 on 2024-05-23 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_customuser_emailisverified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='Oauth_id',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='Oauth_provider',
        ),
        migrations.AddField(
            model_name='customuser',
            name='isOauth',
            field=models.BooleanField(default=False),
        ),
    ]
