# Generated by Django 3.2.7 on 2024-05-23 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20240523_0100'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='Oauthprovider',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
