# Generated by Django 3.2.7 on 2024-05-23 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_customuser_oauthprovider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='Oauthprovider',
            field=models.CharField(blank=True, default='email', max_length=100, null=True),
        ),
    ]
