# Generated by Django 3.2.7 on 2024-06-04 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_customuser_oauthprovider'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='Sex',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='twofactorIsEnabled',
            field=models.BooleanField(default=False),
        ),
    ]
