# Generated by Django 3.2.7 on 2024-06-28 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_auto_20240604_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='verificationToken',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
