# Generated by Django 3.2.7 on 2024-06-28 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_customuser_verificationtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='expiryTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
