# Generated by Django 5.2.6 on 2025-09-20 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_customuser_expirytime'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='fcmToken',
            field=models.TextField(blank=True, null=True),
        ),
    ]
