# Generated by Django 3.2.7 on 2024-05-05 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ICCapp', '0004_auto_20240505_1247'),
        ('customers', '0002_auto_20240503_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ICCapp.organization'),
        ),
    ]
