# Generated by Django 3.2.7 on 2025-08-04 13:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='viewed',
        ),
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('info', 'Info'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error')], default='info', max_length=20),
        ),
        migrations.AddField(
            model_name='notification',
            name='users_viewed',
            field=models.ManyToManyField(blank=True, related_name='notifications_viewed', to=settings.AUTH_USER_MODEL),
        ),
    ]
