# Generated by Django 5.2.6 on 2025-09-20 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_remove_notificationmodified_viewed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationmodified',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='notifications/'),
        ),
    ]
