# Generated by Django 3.2.7 on 2024-08-20 02:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chatroom', '0002_auto_20240819_0322'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmessage',
            name='caption',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='is_reply',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chatroom.groupmessage'),
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='type',
            field=models.CharField(choices=[('text', 'text'), ('file', 'file'), ('image', 'image')], default='text', max_length=10),
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='users_seen',
            field=models.ManyToManyField(blank=True, related_name='seen_messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
