# Generated by Django 3.2.7 on 2024-07-15 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20240714_2041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='token',
            new_name='video_token',
        ),
    ]
