# Generated by Django 3.2.7 on 2024-07-15 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='usersID_that_purchased_product',
            new_name='userIDs_that_bought_this_product',
        ),
    ]
