# Generated by Django 3.2.7 on 2024-07-16 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_rename_video_token_product_product_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='free',
            field=models.BooleanField(default=False),
        ),
    ]
