# Generated by Django 3.2.7 on 2024-07-16 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_free'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product',
            field=models.FileField(blank=True, null=True, upload_to='products/'),
        ),
    ]
