# Generated by Django 3.2.7 on 2024-07-19 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_product_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='number_of_times_bought',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
